### ISSUE TITLE
Add the ability to render an image instead of text

### ISSUE THREAD

**Issue by amorriscode** [amorriscode/book-box#2]
I'd like a config setting that allows you to render a nice image instead of text. This will let you put more books on the list. We can use [HTML CSS To Image](https://htmlcsstoimage.com/). I think the free account is fine and we can update once a day (50 free images a month).

**Comment by amorriscode** [comment]
Did a quick pass on the HTML/CSS.

### HTML

```html
<div class="box">
  <h3 classname="title recent">Recently Read</h3>
  <p>📖 Mastery by Robert Greene</p>
  
  <h3 class="title current">Currently Reading</h3>
  <p>📖 Leonardo da Vinci by Walter Isaacson</p>
</div>
```

### CSS

```css
.box {
  background-color: #fff;
  border: 1px solid #d1d5da;
  border-radius: 3px;
  padding: 16px;
  font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;
  font-size: 12px;
  line-height: 0.5;
  color: #24292e;
}

.title.current {
  margin-top: 32px;
}
```
